name: numeromancy

services:
  model:
    build:
      context: .
      args:
        - USER_ID=${MY_UID}
        - GROUP_ID=${MY_GID}
      target: ${TARGET}
    tty: true
    user: ${MY_UID}:${MY_GID}
    volumes:
      - type: bind
        source: ./data
        target: /home/user/app/data
        bind:
          create_host_path: true
      - type: bind
        source: ./output
        target: /home/user/app/output
        bind:
          create_host_path: true
      - type: bind
        source: ./src
        target: /home/user/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
