MODERN_SETS = [
    "8ed", "mrd", "dst", "5dn",
    "chk", "bok", "sok", "9ed",
    "rav", "gpt", "dis", "csp",
    "tsp", "plc", "fut", "10e",
    "lrw", "mor", "shm", "eve",
    "ala", "con", "arb", "m10",
    "zen", "wwk", "roe", "m11",
    "som", "mbs", "nph", "m12",
    "isd", "dka", "avr", "m13",
    "rtr", "gtc", "dgm", "m14",
    "ths", "bng", "jou", "m15",
    "ktk", "frf", "dtk", "ori",
    "bfz", "ogw", "soi", "emn", "w16",
    "kld", "aer", "akh", "hou", "w17",
    "xln", "rix", "dom", "m19",
    "grn", "rna", "war", "m20",
    "eld", "thb", "iko", "m21",
    "znr", "khm", "stx", "afr",
    "mid", "vow", "neo",
    "mh1", "mh2",
]
